initialPlaylist:  Cubotron #Color Cube #All Videos
initialPlayState: playing #loop_scene

# CUBOTRON
# TESSERACT
# TESSERACT_WALL
# DRACO
# SCARED
stageType: TESSERACT_WALL

# this is temporary.  eventually we'll just have a list of controllers or whatever makes sense, e.g.
# controllers:
#   - type: rabbit
#     ip: 192.168.0.100
#   - type: rabbit
#     ip: 192.168.0.101
#   ...
numRabbits: 0
numTeensies: 0
